### ISSUE TITLE
Make shell script to run this using an emulator

### ISSUE THREAD

**Issue by AtieP** [appusajeev/os-dev-16#1]
Hi, I really want to try this operating system but I can't because my PC uses UEFI without BIOS support and I don't know how to use makefiles, can somebody help me or at least send me the disk image of this OS? Please, I'll appreciate it. Thanks :D

**Comment by alexbelm48** [comment]
If you can't manipulate Makefiles, then you should start learning using them. They're very powerful !

Anyways, I have generated an image disk for you: https://we.tl/t-7nevct1oYp
You'll need to use the `-hda` argument to use the file that you've downloaded as an hard-drive.

Have fun, Alex.

**Comment by AtieP** [comment]
Yeeeeeee thank you @alexbelm48 :smile:
